Added action column to roles.md.

diff --git a/scripts/presubmit b/scripts/presubmit
--- a/scripts/presubmit
+++ b/scripts/presubmit
@@ -1,24 +1,27 @@
 #!/bin/sh
 
+# Colors
+RED=`tput setaf 1`
+GREEN=`tput setaf 2`
+RESET=`tput sgr0`
+
 cd "`dirname "$0"`"/..
 
 nosetests || exit 1
 
 scripts/make-role-page | colordiff doc/roles.md - \
-  || { echo "\nFAIL: doc/roles.md is out of date. Run\n  scripts/make-role-page > doc/roles.md\nto update it."; exit 1; }
+  || { echo "\n${RED}ERROR${RESET}: doc/roles.md is out of date. Run\n  scripts/make-role-page > doc/roles.md\nto update it."; exit 1; }
 
 echo
 ! grep -r "print(" mafia/*.py mafia/*/*.py \
   --exclude=mafia/util.py \
   --exclude=mafia/test/readme_test.py \
   --exclude=mafia/test/test_game.py \
-  || { echo "\nFAIL: Remove leftover print statements before committing."; exit 1; }
+  || { echo "\n${RED}ERROR${RESET}: Remove leftover print statements before committing."; exit 1; }
 
 echo
 ! grep -r "debug=True" mafia/*.py \
   --exclude=mafia/util.py \
-  || { echo "\nFAIL: Remove leftover 'debug=True's before committing."; exit 1; }
+  || { echo "\n${RED}ERROR${RESET}: Remove leftover 'debug=True's before committing."; exit 1; }
 
-GREEN=`tput setaf 2`
-RESET=`tput sgr0`
 echo "Presubmits ${GREEN}PASSED${RESET}.\n"
