Rerefactored Roles to allow pickling.

diff --git a/scripts/presubmit b/scripts/presubmit
--- a/scripts/presubmit
+++ b/scripts/presubmit
@@ -5,8 +5,11 @@ cd "`dirname "$0"`"/..
 nosetests || exit 1
 
 echo
-! grep -r --exclude=mafia/util.py "print(" mafia/*.py ||
-  { echo "\nFAIL: Remove leftover print statements before committing."; exit 1; }
+! grep -r "print(" mafia/*.py mafia/*/*.py \
+  --exclude=mafia/util.py \
+  --exclude=mafia/test/test_game.py \
+  --exclude=mafia/test/readme_test.py \
+  || { echo "\nFAIL: Remove leftover print statements before committing."; exit 1; }
 
 echo
 ! grep -r --exclude=mafia/util.py "debug=True" mafia/*.py mafia/*/*.py ||
